# version: "3.1"

# services:
#   sample:
#     container_name:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - ".:/app"
#       - "/app/node_modules"
#     ports:
#       - 4000:4000

version: "3.1"

services:
  sample:
    container_name: /sochitel_giftcard
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 5000:5000
